### ISSUE TITLE
Error: spawn ENOMEM

### ISSUE THREAD

**Issue by themuddfamily2** [huytd/agar.io-clone#130]
I keep getting this error every 3 runs or so.

Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at Object.<anonymous> (/root/agar.io-clone/node_modules/nodemon/lib/monitor/run.js:18:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by themuddfamily2** [comment]
Turns out it was no RAM...
