### ISSUE TITLE
Critical bug, disappear cells.

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#185]
Hello Dear Developers

If you want to reproduce the bug you have to make 3 cells.
-test1
-test2
-test3

test1 on the firefox
test2 on the google chrome
test3 on the opera

If test 3 will eat test 2 the test 1 can not see the test 3 for mystery bug reason.

Edit console output some Error:

TypeError: Cannot call method 'hasOwnProperty' of null
    at Socket.<anonymous> (/var/www/agar/bin/server/server.js:166:32)
    at Socket.emit (events.js:95:17)
    at Socket.emit (/var/www/agar/node_modules/socket.io/lib/socket.js:129:10)
    at Socket.onclose (/var/www/agar/node_modules/socket.io/lib/socket.js:418:8)
    at Client.onclose (/var/www/agar/node_modules/socket.io/lib/client.js:230:12)
    at Socket.emit (events.js:117:20)
    at Socket.onClose (/var/www/agar/node_modules/socket.io/node_modules/engine.io/lib/socket.js:248:10)
    at WebSocket.g (events.js:180:16)
    at WebSocket.emit (events.js:92:17)
    at WebSocket.Transport.onClose (/var/www/agar/node_modules/socket.io/node_modules/engine.io/lib/transport.js:113:8)

Best Regards
Mateusz

**Comment by themuddfamily2** [comment]
Yeah I caused this bug and no one has accepted my pull to fix it :S

**Comment by neslinesli93** [comment]
What fix exactly?

**Comment by themuddfamily2** [comment]
On line 166 you need to add !playerDisconnected && to the if statement.

**Comment by abalabahaha** [comment]
Seems to be fixed I believe.
