### ISSUE TITLE
Error: Cannot find module 'gulp-babel'

### ISSUE THREAD

**Issue by lordadamson** [huytd/agar.io-clone#293]
first it complained that gulp was not found. so I installed gulp: `npm install -g gulp` then it gets me this error:
```
> agar-clone@1.0.0 start /home/adam/Downloads/agar.io-clone-master
> gulp run


Error: Cannot find module 'gulp-babel'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/adam/Downloads/agar.io-clone-master/gulpfile.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm ERR! not ok code 0
```

I installed gulp-babel, gulp gulp-jshint gulp-nodemon gulp-uglify gulp-util gulp-mocha webpack-stream. but that did not change the error at all.

**Comment by abalabahaha** [comment]
You forgot to do a ```npm install``` in the project directory. The only global package necessary is gulp. Please follow the instructions more carefully next time.
