### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by azorpax** [huytd/agar.io-clone#312]
/home/bstc/agar.io-clone/bin/server/lib/util.js:27
    return Math.sqrt(Math.pow(p2.x - p1.x, 2) + Math.pow(p2.y - p1.y, 2)) - p1
                                ^
TypeError: Cannot read property 'x' of undefined
    at Object.exports.getDistance (/home/bstc/agar.io-clone/bin/server/lib/util.js:27:33)
    at Object.exports.uniformPosition (/home/bstc/agar.io-clone/bin/server/lib/util.js:58:36)
    at addFood (/home/bstc/agar.io-clone/bin/server/server.js:42:56)
    at balanceMass (/home/bstc/agar.io-clone/bin/server/server.js:185:9)
    at gameloop (/home/bstc/agar.io-clone/bin/server/server.js:566:5)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by abalabahaha** [comment]
Have you modified the file? What version of node are you running?

**Comment by huytd** [comment]
You could try this command to see what changed:
```
git status
```

If you didn't changed anything, just reset the codebase and make a pull to get the latest version:
```
git reset --hard
git pull
```

**Comment by azorpax** [comment]
Hi!
I didn't change anything in the code.
The error only occurs when there is a spectator in the game

**Comment by abalabahaha** [comment]
Can you describe how to reproduce this? @azorpax

**Comment by johny90** [comment]
I had this problem too, this happened in spectator mode also. But I have no idea how do I reproduce this error. It just happened when one player kill another player.
