### ISSUE TITLE
bug opening the picture in Mypaint

### ISSUE THREAD

**Issue by sarailemon** [huytd/agar.io-clone#320]
I was doing a painting in my computer and my computes accidentally shut down. When I try to open  the picture, it's saying that there's a bug and a programming error. 

This is what it's saying: 

Traceback (most recent call last):
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 333, update_preview_cb(self=<gui.filehandling.FileHandler object>, file_chooser=<gtk.FileChooserDialog object at 0x3b3aee8 (GtkFileChooserDialog at 0x6b83160)>, preview=<gtk.Image object at 0x3b3ae10 (GtkImage at 0x6c05420)>)
                filename = filename.decode('utf-8')
                pixbuf = helpers.freedesktop_thumbnail(filename)
                if pixbuf:
  File "C:\Program Files\MyPaint\library.zip\lib\helpers.py", line 168, freedesktop_thumbnail(filename=u'C:\\Users\\Sara\\Documents\\pocahontas.ora', pixbuf=None)
                # use the largest stored thumbnail that isn't obsolete
                pixbuf = gdk.pixbuf_new_from_file(fn)
                if file_mtime == pixbuf.get_option("tEXt::Thumb::MTime"):
GError: Failed to load image 'C:\Users\Sara\AppData\Local\mypaint\thumbnails\large\c6fa29742e0d4285ddc18825cbd3a4d8.png': Image has zero width

How do I fix this??

**Comment by IgorAntun** [comment]
Hi @sarailemon, I believe you've come to the wrong page, since this project has nothing to do with Mypaint.
I suggest you to file this issue at https://github.com/mypaint/mypaint/issues, which is Mypaint's official page instead.
