### ISSUE TITLE
TypeError: Cannot read property 'mass' of undefined

### ISSUE THREAD

**Issue by yuzmemak** [huytd/agar.io-clone#389]
Hi,

One of the my test return with following error

TypeError: Cannot read property 'mass' of undefined
    at splitCell (/root/agar_v1/bin/server/server.js:416:21)
    at Socket.<anonymous> (/root/agar_v1/bin/server/server.js:432:17)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Socket.onevent (/root/agar_v1/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/root/agar_v1/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/root/agar_v1/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/root/agar_v1/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/root/agar_v1/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/root/agar_v1/node_modules/socket.io/lib/client.js:175:18)

**Comment by IgorAntun** [comment]
Did you get it to work?

**Comment by HAlexTM** [comment]
Same here, this issue shouldn't be closed

**Comment by abalabahaha** [comment]
It was closed due to lack of response/confirmation

**Comment by HAlexTM** [comment]
Thank you @abalabahaha

**Comment by jusdepatate** [comment]
this bug unistalled `npm` for me...
```
[INFO] Player test connecting!
[INFO] Player test connected!
Total players: 1
/home/jusdepatate/agar.io-clone/bin/server/server.js:437
            if (cell.mass >= c.defaultPlayerMass * 2) {
                     ^

TypeError: Cannot read property 'mass' of undefined
    at splitCell (/home/jusdepatate/agar.io-clone/bin/server/server.js:437:22)
    at Socket.<anonymous> (/home/jusdepatate/agar.io-clone/bin/server/server.js:453:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /home/jusdepatate/agar.io-clone/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[19:50:48] [nodemon] app crashed - waiting for file changes before starting...
^Cjusdepatate@jusdepatate-srv:~/Desktop$ ./agario.sh 
./agario.sh: line 3: npm : can't find command
```
