### ISSUE TITLE
Port 80 Doesn't work

### ISSUE THREAD

**Issue by GrumpyOet** [huytd/agar.io-clone#398]
i changed my port to 80 and it says this

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Object.<anonymous> (/Users/Luke/Downloads/agar/bin/server/server.js:699:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by huytd** [comment]
There might be something already running on your port 80. May be it's Skype, or router management page,... 

There are many way to check it, for example:

```
sudo lsof -i :80
```

**Comment by abalabahaha** [comment]
OSX requires sudo to have applications bind to port 80.

**Comment by IgorAntun** [comment]
Does it work now @GrumpyOet ?

**Comment by IgorAntun** [comment]
Closing this issue for lack of activity and response.
