### ISSUE TITLE
Cannot read property 'mass' of undefined

### ISSUE THREAD

**Issue by ifvictr** [huytd/agar.io-clone#476]
```
2016-12-23T01:52:54.136018+00:00 app[web.1]: /app/bin/server/server.js:415
2016-12-23T01:52:54.136032+00:00 app[web.1]:             if (cell.mass >= c.defaultPlayerMass * 2) {
2016-12-23T01:52:54.136032+00:00 app[web.1]:                     ^
2016-12-23T01:52:54.136033+00:00 app[web.1]: 
2016-12-23T01:52:54.136034+00:00 app[web.1]: TypeError: Cannot read property 'mass' of undefined
2016-12-23T01:52:54.136034+00:00 app[web.1]:     at splitCell (/app/bin/server/server.js:415:21)
2016-12-23T01:52:54.136035+00:00 app[web.1]:     at Socket.<anonymous> (/app/bin/server/server.js:431:17)
2016-12-23T01:52:54.136036+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-23T01:52:54.136037+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2016-12-23T01:52:54.136037+00:00 app[web.1]:     at /app/node_modules/socket.io/lib/socket.js:503:12
2016-12-23T01:52:54.136039+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-12-23T01:52:54.136040+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-23T01:52:54.153039+00:00 app[web.1]: [01:52:54] [nodemon] app crashed - waiting for file changes before starting...
```
This seems to happen when the player reaches a certain mass, around 1,300 or so.

**Comment by ifvictr** [comment]
Closing, didn't see issue #389.
