### ISSUE TITLE
Problem with hosting C9

### ISSUE THREAD

**Issue by empty206** [huytd/agar.io-clone#73]
Hi, I have a problem with the configuration of Agar Clone on Cloud9 (c9.io). I installed everything, I configured IP and port (0.0.0.0), but after starting the application error pops up:

TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (/home/ubuntu/workspace/server/server.js:152:44)
    at Socket.emit (events.js:95:17)
    at Socket.emit (/home/ubuntu/workspace/node_modules/socket.io/lib/socket.js:129:10)
    at Socket.onclose (/home/ubuntu/workspace/node_modules/socket.io/lib/socket.js:418:8)
    at Client.onclose (/home/ubuntu/workspace/node_modules/socket.io/lib/client.js:230:12)
    at Socket.emit (events.js:117:20)
    at Socket.onClose (/home/ubuntu/workspace/node_modules/socket.io/node_modules/engine.io/lib/socket.js:248:10)
    at WebSocket.g (events.js:180:16)                                                                                                                            
    at WebSocket.emit (events.js:92:17)                                                                                                                          
    at WebSocket.Transport.onClose (/home/ubuntu/workspace/node_modules/socket.io/node_modules/engine.io/lib/transport.js:113:8)      

In addition, I give a private message to log data hosting, in order to help. Have you some free hosting to test it yourself to calm the game engine? Thanks in advance for any help! :)

**Comment by Ariamiro** [comment]
solved?

**Comment by empty206** [comment]
Hi,

yes, all OK. :)

--
Pozdrawiam,
Norbert Nyczka
